matrix_me/config/routes.rb
MatrixMe::Application.routes.draw do
  resources :users
  resources :projects
  resources :workspaces do
    resources :navigations
    resources :contexts
    resources :matrix_objects
  end
  
  resources :conversations do
    resources :comments
  end
  
  resources :authorisations
  
  match 'login' => 'authorisations#new'
  match 'logout' => 'authorisations#destroy'
  
  root :to => 'workspaces#index'
  

end

matrix_me/app/models/workspace.rb
class Workspace
  include Mongoid::Document
  
  #field :navigation, :type => Array
  field :context, :type => Hash
  
  embeds_one :matrix_location, :as => :locatable 
  
  field :results_per_page, :type => Integer
  
  field :zoom, :type => String, :default => 'big'
  field :tiles_width, :type => String, :default => '500px'
  
  belongs_to :project
  belongs_to :user
  
  field :current_object_id, :type => String
  
  def matrix_objects
    @query = MatrixObject.all
    self.matrix_location.data.each_with_index do |location, i|
      @query = @query.where("matrix_location.data.#{i}" => location)
    end
    # TODO: implement criteria
    @query.to_a
  end
  
end

matrix_me/app/controllers/workspaces_controller.rb
class WorkspacesController < ApplicationController
  before_filter :check_login
  def index
    @workspaces = @user.workspaces.to_a
    @users = User.where(:id.ne => @user.id)
  end
  def show
    @workspace = Workspace.find(params[:id])
    @project = @workspace.project
    @new_matrix_object = MatrixObject.new
    @object_types = [Member.new, Conversation.new, Content.new]
    @current_object = MatrixObject.find(@workspace.current_object_id) unless @workspace.current_object_id.nil?
  end
  def update
    @workspace = Workspace.find(params[:id])
    @workspace.write_attributes(params[:workspace])
    @workspace.save
    respond_to do |format|
      format.html {redirect_to @workspace}
      format.json {render :json => {:success => true} }
    end
  end
  def create 
    @workspace = Workspace.new(params[:workspace])
    @workspace.matrix_location = MatrixLocation.new(:data => [@workspace.project.template.id.to_s])
    @workspace.save
    redirect_to :back
  end
end

matrix_me/app/views/workspaces/_big_tile.html.erb
<div class='big_tile'>
    <%= image_tag 'http://placekitten.com/160/200', :class => 'thumbnail' %>
    <br />
    <span class='name'><%= big_tile.name %></span>
    <br />
    <span class='description'><%= big_tile.description %></span>
    <br />
    <%= form_for @workspace do |f| %>
        <%= f.hidden_field :current_object_id, :value => big_tile.id %>
        <%= f.submit 'Show' %>
    <% end %>
</div>

matrix_me/app/views/workspaces/_breadcrumb.html.erb
<nav>
    <ul id='breadcrumb'>       
        <% level = 0 %>
        <% current = @project.template %>
        <% if @workspace.matrix_location[0] == @project.template.id.to_s %>
            <li>
                <%= link_to @project.name, edit_workspace_navigation_path(@workspace, @project.template.id) %>
                <ul>
                    <li>
                        <%= link_to 'Public', edit_workspace_navigation_path(@workspace, ([@project.public_template_id] << @workspace.matrix_location.drop(1)).compact.join(MatrixLocation::Separator)) %>
                    </li>
                </ul>
            </li>
        <% else %>
            <li>
                <%= link_to "Public", edit_workspace_navigation_path(@workspace, @project.public_template_id) %>
                <ul>
                    <li>
                        <%= link_to @project.name, edit_workspace_navigation_path(@workspace, ([@project.template.id.to_s] << @workspace.matrix_location.drop(1)).compact.join(MatrixLocation::Separator)) %>
                    </li>
                </ul>
            </li>
        <% end %>
            <li>
                <%= link_to @project.template.name, edit_workspace_navigation_path(@workspace, @workspace.matrix_location[0]) %>
                <% if current.child_template_elements.count > 0 %>
                    <ul>
                        <% current.child_template_elements.each_with_index do |e, i| %>
                            <li>
                                <%= link_to e.name, edit_workspace_navigation_path(@workspace, [@workspace.matrix_location[0], i].join(MatrixLocation::Separator)) %>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </li>
        <% level = 1 %>
        <% while @workspace.matrix_location.count > level %>
            <% current = current.child_template_elements[@workspace.matrix_location[level].to_i] %>
            <% level = level + 1 %> 
            <li>
                <%= link_to current.name, edit_workspace_navigation_path(@workspace, @workspace.matrix_location.first(level).join(MatrixLocation::Separator)) %>
                <% if current.child_template_elements.count > 0 %>
                    <ul>
                        <% current.child_template_elements.each_with_index do |e, i| %>
                            <li>
                                <%= link_to e.name, edit_workspace_navigation_path(@workspace, [@workspace.matrix_location.first(level), i].join(MatrixLocation::Separator)) %>
                            </li>
                        <% end %>
                    </ul>
                <% end %>
            </li>        
        <% end %>
    </ul>
</nav>

matrix_me/app/views/workspaces/_context_menu.html.erb
<h2>Context Menu</h2>

matrix_me/app/views/workspaces/_new_object.html.erb
<h2>New object</h2>
<%= form_for [@workspace, @new_matrix_object] do |f| %>
    <%= f.label :name, 'Name'%>
    <%= f.text_field :name %>
    <br />
    <%= f.label :description, 'Description'%>
    <%= f.text_field :description %>
    <br />
    <%= f.label :_type, 'Object type' %>
    <%= f.select :_type, @object_types.collect{|o| [o._type, o._type]} %>
    <br />
    <div id='attributes'></div>
    <%= f.submit 'Create' %>
<% end %>
<div class='hidden'>
    <% @object_types.each do |o| %>
        <div id=<%= o._type %>-attributes>
            <% o.misc_attributes.each do |key, v| %>
                <%= label_tag "misc_attributes[#{key}]", attribute_label(key) %>
                <%= text_field_tag "misc_attributes[#{key}]" %>
                <br />
            <% end %>
        </div>
    <% end %>
</div>

matrix_me/app/views/workspaces/_small_tile.html.erb
<div class='small_tile'>
    <span class='name'><%= small_tile.name %></span>
    <br />
    <span class='description'><%= small_tile.description %></span>
    <br />
    <%= form_for @workspace do |f| %>
        <%= f.hidden_field :current_object_id, :value => small_tile.id %>
        <%= f.submit 'Show' %>
    <% end %>
</div>

matrix_me/app/views/workspaces/index.html.erb
<h1>Workspaces</h1>
<table id='projects' >
    <% @workspaces.each do |w| %>
        <tr>
            <td>
                <%= link_to w.project.name, workspace_path(w) %>
            </td>
            <td>
                <%= form_for Workspace.new do |f| %>
                    <%= f.select :user, @users.where(:_id.nin => w.project.workspaces.map {|w| w.user_id}).collect {|u| [u.name, u.id]} %>
                    <%= f.hidden_field :project_id, :value => w.project.id %>
                    <%= f.submit 'Invite' %>
                <% end %>
            </td>
        </tr>
    <% end %>
    
</table>
<%= link_to 'Create a new project', new_project_path%>

matrix_me/app/views/workspaces/show.html.erb
<%= content_for :head do %>
    <style type='text/css'>
    #tiles
    {
        width: <%= @workspace.tiles_width %>;
    }
    </style>
<% end %>
<div id='container'>
    <div id='user'>
        <%= @user.name %> | <%= link_to 'Logout', logout_path %>
    </div>
    <div id='header'>
        <h1>MatrixMe</h1>
        <%= render 'breadcrumb' %> 
        <button id='new_object_button'>+</button>
    </div>
    <div id='content'>
        <button id='show_context'>></button>
        <button id='hide_context' class='hidden'><</button>
        <div id='context' class='collapsed'>
            <%= render 'context_menu' %>
        </div>
        <div id='tiles' >
            <%= render :partial => "#{@workspace.zoom}_tile", :collection => @workspace.matrix_objects %>
            <div id='zoom'>
                <%= form_for @workspace do |f| %>
                    <%= f.hidden_field :zoom, :value => @workspace.zoom == 'small' ? 'big' : 'small'  %>
                    <%= f.submit 'Zoom' %>
                <% end %>
            </div>
        </div>
        <div id='separator' class='draggable'>
            
        </div>
        <div id='detail'>
            <%= render @current_object unless @current_object.nil? %>
        </div>
        <br class="clear" />
    </div>
</div>
<div id='full_screen_popup' class='hidden'>
    <div id='popup_container'>
        <div id='new_object'>
            <%= render 'new_object' %>
        </div>
    </div>
</div>
<div id='interface_variables' class='hidden'>
    <%= form_for @workspace, :remote => true, :format => :json do |f| %>   
        <%= f.hidden_field :tiles_width %>
        <%= f.submit :id => 'submit_interface' %>
    <% end %>
</div>